### PR TITLE
fix: make eraser size relative to zoom and consistent with brush

### LINKED ISSUE #25: Eraser size not relative to zoom on minimum size
### Checklist

- [x] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Paint/releases/latest).
- [x] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Paint/issues) or [closed](https://github.com/FossifyOrg/Paint/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [x] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Paint/discussions) or [closed](https://github.com/FossifyOrg/Paint/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [x] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [x] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Paint/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Lenovo Tab M11

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Draw a line
2. Set brush size to the minimum
3. Run eraser through line
4. Zoom in/out
5. Run eraser through line at different position

### Expected behavior

Eraser size should change relative to the zoom.

### Actual behavior

Eraser size doesn't change.

### Screenshots/Screen recordings

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Douniahlt**
### What does this PR do?

This pull request fixes the issue where the eraser stroke size remained visually large, especially at minimum brush size, and did not scale according to zoom level.

### Changes made:
- Removed the hardcoded `MIN_ERASER_WIDTH` condition that forced a minimum size only for the eraser.

Fixes #25 ("Eraser size not relative to zoom on minimum size") as reported.

Let me know if you’d like me to make any adjustments.

### CODE REVIEW

File: app/src/main/kotlin/org/fossify/paint/views/MyCanvas.kt [hunk 1]
```diff
@@ -334,9 +334,9 @@ class MyCanvas(context: Context, attrs: AttributeSet) : View(context, attrs) {
     private fun changePaint(paintOptions: PaintOptions) {
         mPaint.color = if (paintOptions.isEraser) mBackgroundColor else paintOptions.color
         mPaint.strokeWidth = paintOptions.strokeWidth
-        if (paintOptions.isEraser && mPaint.strokeWidth < MIN_ERASER_WIDTH) {
-            mPaint.strokeWidth = MIN_ERASER_WIDTH
-        }
+//        if (paintOptions.isEraser && mPaint.strokeWidth < MIN_ERASER_WIDTH) {
+//            mPaint.strokeWidth = MIN_ERASER_WIDTH
+//        }
```
Comment (naveensingh) [inline app/src/main/kotlin/org/fossify/paint/views/MyCanvas.kt:339]: Remove. Not comment out. 

Only comment out when a change is temporary.

**Review by naveensingh — CHANGES_REQUESTED** [review]

**Comment by naveensingh** [comment]
In addition to https://github.com/FossifyOrg/Paint/pull/30#discussion_r2051677667:

`MIN_ERASER_WIDTH` at [L36](https://github.com/Douniahlt/Paint-issue25/blob/b3e2769692a62ecdf0c9500aa5b371a64511e83d/app/src/main/kotlin/org/fossify/paint/views/MyCanvas.kt#L36) is not used anymore and should be removed.

**Review by naveensingh — APPROVED** [review]
Seems to work fine, thank you!
